version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ../deployment/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ../deployment/monitoring/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    depends_on:
      - prometheus
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  grafana-data:
